require "activerecord-postgres-hstore/railties"
require "activerecord-postgres-hstore/string"
require "activerecord-postgres-hstore/hash"
require "activerecord-postgres-hstore/coder"
require "activerecord-postgres-hstore/array"